"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from werkzeug.exceptions import HTTPException
from werkzeug.routing import Rule
from werkzeug.wrappers import Request as RequestBase, Response as ResponseBase

class JSONMixin:
    @property
    def is_json(self) -> bool:
        ...
    
    @property
    def json(self):
        ...
    
    def get_json(self, force: bool = ..., silent: bool = ..., cache: bool = ...):
        ...
    
    def on_json_loading_failed(self, e: Any) -> None:
        ...
    


class Request(RequestBase, JSONMixin):
    url_rule: Optional[Rule] = ...
    view_args: Dict[str, Any] = ...
    routing_exception: Optional[HTTPException] = ...
    @property
    def max_content_length(self) -> Optional[int]:
        ...
    
    @property
    def endpoint(self) -> Optional[str]:
        ...
    
    @property
    def blueprint(self) -> Optional[str]:
        ...
    


class Response(ResponseBase, JSONMixin):
    default_mimetype: Optional[str] = ...
    @property
    def max_cookie_size(self) -> int:
        ...
    


