"""
This type stub file was generated by pyright.
"""

from jsonschema import ValidationError
from .base import BR_SANITIZER, Flasgger, LazyJSONEncoder, MK_SANITIZER, NO_SANITIZER, Swagger
from .utils import LazyString, apispec_to_template, swag_from, validate
from .marshmallow_apispec import APISpec, Schema, SwaggerView, fields
from .constants import OPTIONAL_FIELDS

__version__ = '0.9.3'
__author__ = 'Bruno Rocha'
__email__ = 'rochacbruno@gmail.com'
